package Utils;

import java.util.ArrayList;
import java.util.Collections;

import Readers.AntiSpamFilesReader;
import Readers.ReadConfiguration;

/**
 * Calculator for the best FN and FP value generated by the AntiSpamFilter and respective rules
 */
public class OptimalCalculator {

	private ReadConfiguration rc;
	private AntiSpamFilesReader asfr;
	private String ruleSet;
	private int BestFset;
	private double FP;
	private double FN;

	/**
	 * Calculates the amount of FP and FN after an Optimal Configuration had been generated 
	 * 
	 * @param rc
	 * @param asfr
	 */
	public OptimalCalculator(ReadConfiguration rc, AntiSpamFilesReader asfr) {
		this.rc = rc;
		this.asfr = asfr;
		calculateBestFset();
		getRuleSet();
		writeBestRules();
	}

	/**
	 * @return index of best set of FP and FN values
	 */
	public int calculateBestFset() { //1º
		ArrayList<Double> FP = asfr.getFP();
		ArrayList<Double> FN = asfr.getFN();
		ArrayList<Double> bestSet = new ArrayList<Double>();
		for(int x = 0;x < FP.size();x++) {
			double b = Math.sqrt(Math.pow(FP.get(x), 2)+ Math.pow(FN.get(x), 2));
			bestSet.add(b);
		}
		BestFset = bestSet.indexOf(Collections.min(bestSet));
		this.FP = FP.get(BestFset);
		this.FN = FN.get(BestFset); 
		return BestFset;
	}

	/**
	 * @return the rules weight of the best FN and FP set
	 */
	public String getRuleSet() { //2º
		ruleSet = asfr.getRuleSet().get(BestFset);
		return ruleSet;
	}

	/**
	 * Writes the rules generated by AntiSpamFilter to rules.cf file
	 */
	public void writeBestRules() { //3º
		String[] rulesWeight = ruleSet.split(" ");
		int i = 0;
		for(String rule : rc.getConfiguration().keySet()) {
			rc.getConfiguration().put(rule, rulesWeight[i]);
			i++;
		}
		rc.writeConfig();
	}
	
	/**
	 * @return FN value
	 */
	public double getFN() {
		return FN;
	}
	
	/**
	 * @return FP value
	 */
	public double getFP() {
		return FP;
	}
	
}
